apiVersion: apps/v1
kind: Deployment
metadata:
  name: zero-demo-net
  labels:
    app: zero-demo-net
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: zero-demo-net
  template:
    metadata:
      labels:
        app: zero-demo-net
    spec:
      containers:
      - name: app
        image: wojciech11/zero-kube-demo-net:1.0.0
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /healthz
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /ready
            port: 80
          # Intial delay is set to a high value to have a better
          # visibility of the ramped deployment
          initialDelaySeconds: 10
          periodSeconds: 5
